# Generated by Django 3.2.11 on 2022-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('runoob', models.TextField()),
                ('runoob_author', models.CharField(max_length=60)),
                ('submission_date', models.DateField()),

            ],
        ),
    ]
