# Generated by Django 3.2.11 on 2022-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
